run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - revive    # Replacement for golint (enforces comments)
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam

linters-settings:
  revive:
    rules:
      - name: exported
      - name: package-comments
  goimports:
    local-prefixes: github.com/off-by-2/sal

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
