// Package repository implements data access for the Salvia application.
package repository

import (
	"context"
	"fmt"
	"time"

	"github.com/off-by-2/sal/internal/database"
)

// Organization represents a row in the organizations table.
type Organization struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
	OwnerID   string    `json:"owner_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// OrganizationRepository handles database operations for organizations.
type OrganizationRepository struct {
	db *database.Postgres
}

// NewOrganizationRepository creates a new OrganizationRepository.
func NewOrganizationRepository(db *database.Postgres) *OrganizationRepository {
	return &OrganizationRepository{db: db}
}

// CreateOrg inserts a new organization.
func (r *OrganizationRepository) CreateOrg(ctx context.Context, o *Organization) error {
	query := `
		INSERT INTO organizations (
			name, owner_user_id
		) VALUES (
			$1, $2
		) RETURNING id, slug, created_at, updated_at`

	// Slug is generated by DB trigger, so we scan it back
	err := r.db.Pool.QueryRow(ctx, query,
		o.Name, o.OwnerID,
	).Scan(&o.ID, &o.Slug, &o.CreatedAt, &o.UpdatedAt)

	if err != nil {
		return fmt.Errorf("failed to create organization: %w", err)
	}

	return nil
}
